//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace com.jajago.SA.Biz
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class jajagoEntities1 : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“jajagoEntities1”部分中的连接字符串初始化新 jajagoEntities1 对象。
        /// </summary>
        public jajagoEntities1() : base("name=jajagoEntities1", "jajagoEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 jajagoEntities1 对象。
        /// </summary>
        public jajagoEntities1(string connectionString) : base(connectionString, "jajagoEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 jajagoEntities1 对象。
        /// </summary>
        public jajagoEntities1(EntityConnection connection) : base(connection, "jajagoEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobileInTaxon> MobileInTaxons
        {
            get
            {
                if ((_MobileInTaxons == null))
                {
                    _MobileInTaxons = base.CreateObjectSet<MobileInTaxon>("MobileInTaxons");
                }
                return _MobileInTaxons;
            }
        }
        private ObjectSet<MobileInTaxon> _MobileInTaxons;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Mobile> Mobiles
        {
            get
            {
                if ((_Mobiles == null))
                {
                    _Mobiles = base.CreateObjectSet<Mobile>("Mobiles");
                }
                return _Mobiles;
            }
        }
        private ObjectSet<Mobile> _Mobiles;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobileTaxonomy> MobileTaxonomies
        {
            get
            {
                if ((_MobileTaxonomies == null))
                {
                    _MobileTaxonomies = base.CreateObjectSet<MobileTaxonomy>("MobileTaxonomies");
                }
                return _MobileTaxonomies;
            }
        }
        private ObjectSet<MobileTaxonomy> _MobileTaxonomies;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobileTaxon> MobileTaxons
        {
            get
            {
                if ((_MobileTaxons == null))
                {
                    _MobileTaxons = base.CreateObjectSet<MobileTaxon>("MobileTaxons");
                }
                return _MobileTaxons;
            }
        }
        private ObjectSet<MobileTaxon> _MobileTaxons;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 MobileInTaxons EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobileInTaxons(MobileInTaxon mobileInTaxon)
        {
            base.AddObject("MobileInTaxons", mobileInTaxon);
        }
    
        /// <summary>
        /// 用于向 Mobiles EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobiles(Mobile mobile)
        {
            base.AddObject("Mobiles", mobile);
        }
    
        /// <summary>
        /// 用于向 MobileTaxonomies EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobileTaxonomies(MobileTaxonomy mobileTaxonomy)
        {
            base.AddObject("MobileTaxonomies", mobileTaxonomy);
        }
    
        /// <summary>
        /// 用于向 MobileTaxons EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobileTaxons(MobileTaxon mobileTaxon)
        {
            base.AddObject("MobileTaxons", mobileTaxon);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="jajagoModel1", Name="Mobile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mobile : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Mobile 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Mobile CreateMobile(global::System.Int64 id)
        {
            Mobile mobile = new Mobile();
            mobile.id = id;
            return mobile;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String standard
        {
            get
            {
                return _standard;
            }
            set
            {
                OnstandardChanging(value);
                ReportPropertyChanging("standard");
                _standard = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("standard");
                OnstandardChanged();
            }
        }
        private global::System.String _standard;
        partial void OnstandardChanging(global::System.String value);
        partial void OnstandardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String props
        {
            get
            {
                return _props;
            }
            set
            {
                OnpropsChanging(value);
                ReportPropertyChanging("props");
                _props = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("props");
                OnpropsChanged();
            }
        }
        private global::System.String _props;
        partial void OnpropsChanging(global::System.String value);
        partial void OnpropsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] small_icon
        {
            get
            {
                return StructuralObject.GetValidValue(_small_icon);
            }
            set
            {
                Onsmall_iconChanging(value);
                ReportPropertyChanging("small_icon");
                _small_icon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("small_icon");
                Onsmall_iconChanged();
            }
        }
        private global::System.Byte[] _small_icon;
        partial void Onsmall_iconChanging(global::System.Byte[] value);
        partial void Onsmall_iconChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String photo_path
        {
            get
            {
                return _photo_path;
            }
            set
            {
                Onphoto_pathChanging(value);
                ReportPropertyChanging("photo_path");
                _photo_path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo_path");
                Onphoto_pathChanged();
            }
        }
        private global::System.String _photo_path;
        partial void Onphoto_pathChanging(global::System.String value);
        partial void Onphoto_pathChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="jajagoModel1", Name="MobileInTaxon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobileInTaxon : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobileInTaxon 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobileInTaxon CreateMobileInTaxon(global::System.Int64 id)
        {
            MobileInTaxon mobileInTaxon = new MobileInTaxon();
            mobileInTaxon.id = id;
            return mobileInTaxon;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> mobile_id
        {
            get
            {
                return _mobile_id;
            }
            set
            {
                Onmobile_idChanging(value);
                ReportPropertyChanging("mobile_id");
                _mobile_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mobile_id");
                Onmobile_idChanged();
            }
        }
        private Nullable<global::System.Int64> _mobile_id;
        partial void Onmobile_idChanging(Nullable<global::System.Int64> value);
        partial void Onmobile_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> taxonomy_id
        {
            get
            {
                return _taxonomy_id;
            }
            set
            {
                Ontaxonomy_idChanging(value);
                ReportPropertyChanging("taxonomy_id");
                _taxonomy_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxonomy_id");
                Ontaxonomy_idChanged();
            }
        }
        private Nullable<global::System.Int64> _taxonomy_id;
        partial void Ontaxonomy_idChanging(Nullable<global::System.Int64> value);
        partial void Ontaxonomy_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> taxon_id
        {
            get
            {
                return _taxon_id;
            }
            set
            {
                Ontaxon_idChanging(value);
                ReportPropertyChanging("taxon_id");
                _taxon_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxon_id");
                Ontaxon_idChanged();
            }
        }
        private Nullable<global::System.Int64> _taxon_id;
        partial void Ontaxon_idChanging(Nullable<global::System.Int64> value);
        partial void Ontaxon_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="jajagoModel1", Name="MobileTaxon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobileTaxon : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobileTaxon 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobileTaxon CreateMobileTaxon(global::System.Int64 id)
        {
            MobileTaxon mobileTaxon = new MobileTaxon();
            mobileTaxon.id = id;
            return mobileTaxon;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> taxonomy_id
        {
            get
            {
                return _taxonomy_id;
            }
            set
            {
                Ontaxonomy_idChanging(value);
                ReportPropertyChanging("taxonomy_id");
                _taxonomy_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxonomy_id");
                Ontaxonomy_idChanged();
            }
        }
        private Nullable<global::System.Int64> _taxonomy_id;
        partial void Ontaxonomy_idChanging(Nullable<global::System.Int64> value);
        partial void Ontaxonomy_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> parent_id
        {
            get
            {
                return _parent_id;
            }
            set
            {
                Onparent_idChanging(value);
                ReportPropertyChanging("parent_id");
                _parent_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parent_id");
                Onparent_idChanged();
            }
        }
        private Nullable<global::System.Int64> _parent_id;
        partial void Onparent_idChanging(Nullable<global::System.Int64> value);
        partial void Onparent_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="jajagoModel1", Name="MobileTaxonomy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobileTaxonomy : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobileTaxonomy 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobileTaxonomy CreateMobileTaxonomy(global::System.Int64 id)
        {
            MobileTaxonomy mobileTaxonomy = new MobileTaxonomy();
            mobileTaxonomy.id = id;
            return mobileTaxonomy;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
    }

    #endregion
    
}
