//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace com.jajago.Biz
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class MobilesEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“MobilesEntities”部分中的连接字符串初始化新 MobilesEntities 对象。
        /// </summary>
        public MobilesEntities() : base("name=MobilesEntities", "MobilesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MobilesEntities 对象。
        /// </summary>
        public MobilesEntities(string connectionString) : base(connectionString, "MobilesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MobilesEntities 对象。
        /// </summary>
        public MobilesEntities(EntityConnection connection) : base(connection, "MobilesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobileAttribute> MobileAttributes
        {
            get
            {
                if ((_MobileAttributes == null))
                {
                    _MobileAttributes = base.CreateObjectSet<MobileAttribute>("MobileAttributes");
                }
                return _MobileAttributes;
            }
        }
        private ObjectSet<MobileAttribute> _MobileAttributes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobileInAttribute> MobileInAttributes
        {
            get
            {
                if ((_MobileInAttributes == null))
                {
                    _MobileInAttributes = base.CreateObjectSet<MobileInAttribute>("MobileInAttributes");
                }
                return _MobileInAttributes;
            }
        }
        private ObjectSet<MobileInAttribute> _MobileInAttributes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobileInTaxon> MobileInTaxons
        {
            get
            {
                if ((_MobileInTaxons == null))
                {
                    _MobileInTaxons = base.CreateObjectSet<MobileInTaxon>("MobileInTaxons");
                }
                return _MobileInTaxons;
            }
        }
        private ObjectSet<MobileInTaxon> _MobileInTaxons;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobilePhoto> MobilePhotos
        {
            get
            {
                if ((_MobilePhotos == null))
                {
                    _MobilePhotos = base.CreateObjectSet<MobilePhoto>("MobilePhotos");
                }
                return _MobilePhotos;
            }
        }
        private ObjectSet<MobilePhoto> _MobilePhotos;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Mobile> Mobiles
        {
            get
            {
                if ((_Mobiles == null))
                {
                    _Mobiles = base.CreateObjectSet<Mobile>("Mobiles");
                }
                return _Mobiles;
            }
        }
        private ObjectSet<Mobile> _Mobiles;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobileTaxonomy> MobileTaxonomies
        {
            get
            {
                if ((_MobileTaxonomies == null))
                {
                    _MobileTaxonomies = base.CreateObjectSet<MobileTaxonomy>("MobileTaxonomies");
                }
                return _MobileTaxonomies;
            }
        }
        private ObjectSet<MobileTaxonomy> _MobileTaxonomies;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MobileTaxon> MobileTaxons
        {
            get
            {
                if ((_MobileTaxons == null))
                {
                    _MobileTaxons = base.CreateObjectSet<MobileTaxon>("MobileTaxons");
                }
                return _MobileTaxons;
            }
        }
        private ObjectSet<MobileTaxon> _MobileTaxons;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 MobileAttributes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobileAttributes(MobileAttribute mobileAttribute)
        {
            base.AddObject("MobileAttributes", mobileAttribute);
        }
    
        /// <summary>
        /// 用于向 MobileInAttributes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobileInAttributes(MobileInAttribute mobileInAttribute)
        {
            base.AddObject("MobileInAttributes", mobileInAttribute);
        }
    
        /// <summary>
        /// 用于向 MobileInTaxons EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobileInTaxons(MobileInTaxon mobileInTaxon)
        {
            base.AddObject("MobileInTaxons", mobileInTaxon);
        }
    
        /// <summary>
        /// 用于向 MobilePhotos EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobilePhotos(MobilePhoto mobilePhoto)
        {
            base.AddObject("MobilePhotos", mobilePhoto);
        }
    
        /// <summary>
        /// 用于向 Mobiles EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobiles(Mobile mobile)
        {
            base.AddObject("Mobiles", mobile);
        }
    
        /// <summary>
        /// 用于向 MobileTaxonomies EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobileTaxonomies(MobileTaxonomy mobileTaxonomy)
        {
            base.AddObject("MobileTaxonomies", mobileTaxonomy);
        }
    
        /// <summary>
        /// 用于向 MobileTaxons EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMobileTaxons(MobileTaxon mobileTaxon)
        {
            base.AddObject("MobileTaxons", mobileTaxon);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobilesModel", Name="Mobile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mobile : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Mobile 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Mobile CreateMobile(global::System.Int64 id)
        {
            Mobile mobile = new Mobile();
            mobile.id = id;
            return mobile;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> price_shop
        {
            get
            {
                return _price_shop;
            }
            set
            {
                Onprice_shopChanging(value);
                ReportPropertyChanging("price_shop");
                _price_shop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price_shop");
                Onprice_shopChanged();
            }
        }
        private Nullable<global::System.Decimal> _price_shop;
        partial void Onprice_shopChanging(Nullable<global::System.Decimal> value);
        partial void Onprice_shopChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> price_market
        {
            get
            {
                return _price_market;
            }
            set
            {
                Onprice_marketChanging(value);
                ReportPropertyChanging("price_market");
                _price_market = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price_market");
                Onprice_marketChanged();
            }
        }
        private Nullable<global::System.Decimal> _price_market;
        partial void Onprice_marketChanging(Nullable<global::System.Decimal> value);
        partial void Onprice_marketChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String img_url
        {
            get
            {
                return _img_url;
            }
            set
            {
                Onimg_urlChanging(value);
                ReportPropertyChanging("img_url");
                _img_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("img_url");
                Onimg_urlChanged();
            }
        }
        private global::System.String _img_url;
        partial void Onimg_urlChanging(global::System.String value);
        partial void Onimg_urlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Int32> _status;
        partial void OnstatusChanging(Nullable<global::System.Int32> value);
        partial void OnstatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobilesModel", Name="MobileAttribute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobileAttribute : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobileAttribute 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobileAttribute CreateMobileAttribute(global::System.Int64 id)
        {
            MobileAttribute mobileAttribute = new MobileAttribute();
            mobileAttribute.id = id;
            return mobileAttribute;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobilesModel", Name="MobileInAttribute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobileInAttribute : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobileInAttribute 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobileInAttribute CreateMobileInAttribute(global::System.Int64 id)
        {
            MobileInAttribute mobileInAttribute = new MobileInAttribute();
            mobileInAttribute.id = id;
            return mobileInAttribute;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> mobile_id
        {
            get
            {
                return _mobile_id;
            }
            set
            {
                Onmobile_idChanging(value);
                ReportPropertyChanging("mobile_id");
                _mobile_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mobile_id");
                Onmobile_idChanged();
            }
        }
        private Nullable<global::System.Int64> _mobile_id;
        partial void Onmobile_idChanging(Nullable<global::System.Int64> value);
        partial void Onmobile_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> attribute_id
        {
            get
            {
                return _attribute_id;
            }
            set
            {
                Onattribute_idChanging(value);
                ReportPropertyChanging("attribute_id");
                _attribute_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("attribute_id");
                Onattribute_idChanged();
            }
        }
        private Nullable<global::System.Int64> _attribute_id;
        partial void Onattribute_idChanging(Nullable<global::System.Int64> value);
        partial void Onattribute_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobilesModel", Name="MobileInTaxon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobileInTaxon : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobileInTaxon 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobileInTaxon CreateMobileInTaxon(global::System.Int64 id)
        {
            MobileInTaxon mobileInTaxon = new MobileInTaxon();
            mobileInTaxon.id = id;
            return mobileInTaxon;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> mobile_id
        {
            get
            {
                return _mobile_id;
            }
            set
            {
                Onmobile_idChanging(value);
                ReportPropertyChanging("mobile_id");
                _mobile_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mobile_id");
                Onmobile_idChanged();
            }
        }
        private Nullable<global::System.Int64> _mobile_id;
        partial void Onmobile_idChanging(Nullable<global::System.Int64> value);
        partial void Onmobile_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> taxonomy_id
        {
            get
            {
                return _taxonomy_id;
            }
            set
            {
                Ontaxonomy_idChanging(value);
                ReportPropertyChanging("taxonomy_id");
                _taxonomy_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxonomy_id");
                Ontaxonomy_idChanged();
            }
        }
        private Nullable<global::System.Int64> _taxonomy_id;
        partial void Ontaxonomy_idChanging(Nullable<global::System.Int64> value);
        partial void Ontaxonomy_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> taxon_id
        {
            get
            {
                return _taxon_id;
            }
            set
            {
                Ontaxon_idChanging(value);
                ReportPropertyChanging("taxon_id");
                _taxon_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxon_id");
                Ontaxon_idChanged();
            }
        }
        private Nullable<global::System.Int64> _taxon_id;
        partial void Ontaxon_idChanging(Nullable<global::System.Int64> value);
        partial void Ontaxon_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobilesModel", Name="MobilePhoto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobilePhoto : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobilePhoto 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobilePhoto CreateMobilePhoto(global::System.Int64 id)
        {
            MobilePhoto mobilePhoto = new MobilePhoto();
            mobilePhoto.id = id;
            return mobilePhoto;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> mobile_id
        {
            get
            {
                return _mobile_id;
            }
            set
            {
                Onmobile_idChanging(value);
                ReportPropertyChanging("mobile_id");
                _mobile_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mobile_id");
                Onmobile_idChanged();
            }
        }
        private Nullable<global::System.Int64> _mobile_id;
        partial void Onmobile_idChanging(Nullable<global::System.Int64> value);
        partial void Onmobile_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String path
        {
            get
            {
                return _path;
            }
            set
            {
                OnpathChanging(value);
                ReportPropertyChanging("path");
                _path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("path");
                OnpathChanged();
            }
        }
        private global::System.String _path;
        partial void OnpathChanging(global::System.String value);
        partial void OnpathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_main
        {
            get
            {
                return _is_main;
            }
            set
            {
                Onis_mainChanging(value);
                ReportPropertyChanging("is_main");
                _is_main = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_main");
                Onis_mainChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_main;
        partial void Onis_mainChanging(Nullable<global::System.Boolean> value);
        partial void Onis_mainChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobilesModel", Name="MobileTaxon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobileTaxon : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobileTaxon 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobileTaxon CreateMobileTaxon(global::System.Int64 id)
        {
            MobileTaxon mobileTaxon = new MobileTaxon();
            mobileTaxon.id = id;
            return mobileTaxon;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> taxonomy_id
        {
            get
            {
                return _taxonomy_id;
            }
            set
            {
                Ontaxonomy_idChanging(value);
                ReportPropertyChanging("taxonomy_id");
                _taxonomy_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("taxonomy_id");
                Ontaxonomy_idChanged();
            }
        }
        private Nullable<global::System.Int64> _taxonomy_id;
        partial void Ontaxonomy_idChanging(Nullable<global::System.Int64> value);
        partial void Ontaxonomy_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> parent_id
        {
            get
            {
                return _parent_id;
            }
            set
            {
                Onparent_idChanging(value);
                ReportPropertyChanging("parent_id");
                _parent_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parent_id");
                Onparent_idChanged();
            }
        }
        private Nullable<global::System.Int64> _parent_id;
        partial void Onparent_idChanging(Nullable<global::System.Int64> value);
        partial void Onparent_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobilesModel", Name="MobileTaxonomy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MobileTaxonomy : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MobileTaxonomy 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static MobileTaxonomy CreateMobileTaxonomy(global::System.Int64 id)
        {
            MobileTaxonomy mobileTaxonomy = new MobileTaxonomy();
            mobileTaxonomy.id = id;
            return mobileTaxonomy;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
    }

    #endregion
    
}
